<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Temp extends Model
{
  
    public static function mock()
    {
        return collect([

            (object)[
                'id' => 1,
                'code' => 'SP-BLON  6-20',
                'name' => 'Bulong inox M6-20',
                'description' => 'Bulong inox M6-20',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'Bulong inox M6-20.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 2,
                'code' => 'SP-BLON  8-20',
                'name' => 'Bulong inox M8-20',
                'description' => 'Bulong inox M8-20',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'Bulong inox M6-20.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 3,
                'code' => 'SP-WASH 06',
                'name' => 'Flat Washer INOX M6',
                'description' => 'Flat Washer INOX M6',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-WASH 06.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 4,
                'code' => 'SP-WASH 05',
                'name' => 'Flat Washer INOX M5',
                'description' => 'Flat Washer INOX M5',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-WASH 06.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],

            (object)[
                'id' => 5,
                'code' => 'SP-BELT B52',
                'name' => 'Belt B-52 (For Boiler)',
                'description' => 'Belt B-52 (For Boiler)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-BELT B52.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],

            (object)[
                'id' => 6,
                'code' => 'SP-RELA 5-220-8S',
                'name' => 'Relay 230VAC 12A 8Pins RXM2AB2P7, (Schneider)',
                'description' => 'Relay 230VAC 12A 8Pins RXM2AB2P7, (Schneider)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-RELA 5-220-8S.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 7,
                'code' => 'SP-DBIN 05',
                'name' => 'Drill Bit Inox Ø5mm HSS, NICO',
                'description' => 'Drill Bit Inox Ø5mm HSS, NICO',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-DBIN 05.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 8,
                'code' => 'SP-1294',
                'name' => 'U-Heater 2Kw 220V L450mm',
                'description' => 'U-Heater 2Kw 220V L450mm',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-1294.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 9,
                'code' => 'SP-WHEL B',
                'name' => 'Brown Polishing Disc D100-d16',
                'description' => 'Brown Polishing Disc D100-d16',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-WHEL B.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],

            (object)[
                'id' => 10,
                'code' => 'SP-1663',
                'name' => 'Resistance Ø10mm x L250mm 1Kw (For Boiling Syrup)',
                'description' => 'Resistance Ø10mm x L250mm 1Kw (For Boiling Syrup)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-1663.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],

            (object)[
                'id' => 11,
                'code' => 'SP-BRIN 30207',
                'name' => 'Bearing 30207,ZZ J2/Q for Gansons',
                'description' => 'Bearing 30207,ZZ J2/Q for Gansons',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-BRIN 30207.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 12,
                'code' => 'SP-BRIN 30206',
                'name' => 'Bearing 30206 ,ZZ /Q for Gansons',
                'description' => 'Bearing 30206 ,ZZ /Q for Gansons',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-BRIN 30206.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],

            (object)[
                'id' => 13,
                'code' => 'SP-PURE DIF 3P-63A',
                'name' => 'Inter. Differentiel 3P-63A 30mA (RCCB),SCHEIDER',
                'description' => 'Inter. Differentiel 3P-63A 30mA (RCCB),SCHEIDER',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-PURE DIF 3P-63A.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 14,
                'code' => 'SP-SEAL 50-68',
                'name' => 'SEAL TC 50-68-9 (Cooking Candy Machine)',
                'description' => 'SEAL TC 50-68-9 (Cooking Candy Machine)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-SEAL 50-68.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 15,
                'code' => 'SP-GS-150',
                'name' => 'Grinding Stone 150-20-32 (ផ្លែសំលៀង ម៉ត់)',
                'description' => 'Grinding Stone 150-20-32 (ផ្លែសំលៀង ម៉ត់)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'Grinding Stone 150-20-32.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 16,
                'code' => 'SP-SEAL 75-95-12T',
                'name' => 'Seal TC 75-95-12',
                'description' => 'Seal TC 75-95-12',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'Seal TC 75-95-12.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 17,
                'code' => 'SP-ACNT I10- 8',
                'name' => 'Pneumatic Fitting PU 10-08',
                'description' => 'Pneumatic Fitting PU 10-08',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-ACNT I10- 82.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 18,
                'code' => 'SP-VALV 4-210-08',
                'name' => 'Solenoid Valve TG2521-08 24VDC, (STNC)',
                'description' => 'Solenoid Valve TG2521-08 24VDC, (STNC)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-VALV 4-210-08.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 19,
                'code' => 'SP-ELPEN',
                'name' => 'Electric Pen -Germany',
                'description' => 'Electric Pen -Germany',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-ELPEN.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 20,
                'code' => 'SP-GS-100',
                'name' => 'Grinding Stone Ø100mm(ផ្លែឆាប)',
                'description' => 'Grinding Stone Ø100mm(ផ្លែឆាប)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-GS-100.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 21,
                'code' => 'SP-LACU 6-12CAR',
                'name' => 'Lathing Cutter In Carbon 6x12x140 (ខ្សែខ្ចៅក្នុង)',
                'description' => 'Lathing Cutter In Carbon 6x12x140 (ខ្សែខ្ចៅក្នុង)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-LACU 6-12CAR.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 22,
                'code' => 'SP-WTAP G1/8',
                'name' => 'Withworth Taper G1/8" ',
                'description' => 'Withworth Taper G1/8" ',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-WTAP G1-8.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 23,
                'code' => 'SP-BALL240',
                'name' => 'BALLAST 100-240VAC / 21-35VDC',
                'description' => 'BALLAST 100-240VAC / 21-35VDC',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-BALL240.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 24,
                'code' => 'SP-LACU 6-100',
                'name' => 'Lathing Cutter In Carbon 6x100(កាំបិតបកក្នុង)',
                'description' => 'Lathing Cutter In Carbon 6x100(កាំបិតបកក្នុង)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-LACU 6-100.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 25,
                'code' => 'SP-SOLE SA',
                'name' => 'Solenoid Coil SA-992 0.5Kg 220VAC+Foot (Full Set)',
                'description' => 'Solenoid Coil SA-992 0.5Kg 220VAC+Foot (Full Set)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-SOLE SA.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],

            (object)[
                'id' => 26,
                'code' => 'SP-1119',
                'name' => 'Belt for Plastic ironing machine model SF-150',
                'description' => 'Belt for Plastic ironing machine model SF-150',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'placeholder.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 27,
                'code' => 'SP-BRIN 6203',
                'name' => 'Bearing 6203-ZZ , NTN',
                'description' => 'Bearing 6203-ZZ , NTN',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-BRIN 6203.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],



            (object)[
                'id' => 28,
                'code' => 'SP-0450',
                'name' => 'Copper Brush-Small, (ច្រាសស្ពាន់)',
                'description' => 'Copper Brush-Small, (ច្រាសស្ពាន់)',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-0450.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 29,
                'code' => 'SP-BOLTHEX 6-20',
                'name' => 'Hex Bolt INOX M6-20',
                'description' => 'Hex Bolt INOX M6-20',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-BOLTHEX 6-20.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 30,
                'code' => 'SP-WASH 12',
                'name' => 'Flat Washer INOX M12',
                'description' => 'Flat Washer INOX M12',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-WASH 12.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 31,
                'code' => 'SP-BLON 10-50',
                'name' => 'Bulong INOX M10-50',
                'description' => 'Bulong INOX M10-50',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-BLON 10-50.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 32,
                'code' => 'SP-NUTM 8',
                'name' => 'NUT INOX M8',
                'description' => 'NUT INOX M8',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'SP-NUTM 8.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],
            (object)[
                'id' => 33,
                'code' => 'MS-TARO M8',
                'name' => 'Taroo Inox M8 (ផ្លែតារ៉ូ),HTC',
                'description' => 'Taroo Inox M8 (ផ្លែតារ៉ូ),HTC',
                'stock_qty' => 99,
                'vat' => 0,
                'discount_percent' => 0,
                'image' => 'MS-TARO M8.jpg',
                'category' => 'Accessory',
                'price' => 1,
                'cost' => 1,
                'unit' => 'PCS'
            ],

        ]);
    }
}
